# GitHub Actions definition for CI build.

name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  WinBuildTest:
    name: Windows build and test
    runs-on: windows-2022  # 2019 is not sufficient, Windows 21H1+ is best for ReFS bug fixes
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        # No "with: dotnet-version" specified -> use global.json
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Shrink C drive and create a ReFS E drive
        run: |
          echo SELECT VOLUME C:                  >DiskPartScript.txt
          echo SHRINK                           >>DiskPartScript.txt
          echo CREATE PARTITION PRIMARY         >>DiskPartScript.txt
          echo SELECT PARTITION 5               >>DiskPartScript.txt
          echo FORMAT FS=ReFS LABEL=ReFS Test   >>DiskPartScript.txt
          echo ASSIGN LETTER=E                  >>DiskPartScript.txt
          echo LIST VOLUME                      >>DiskPartScript.txt
          echo SELECT VOLUME 4                  >>DiskPartScript.txt
          echo ASSIGN MOUNT=C:\ReFS             >>DiskPartScript.txt

          diskpart /s DiskPartScript.txt
          if not exist E:\ echo ERROR: diskpart failed && exit /b 1
          if not exist C:\ReFS echo ERROR: diskpart failed && exit /b 1

          @rem CODESYNC: WindowsReFSDriveSession.cs
          SETX CoW_Test_ReFS_Drive E:\
          exit /b 0
        shell: cmd
      - run: dotnet test --no-restore
